name: tiar_pilot
description: الدهشان — تطبيق الطيار
publish_to: 'none'
version: 1.9.2+11

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  geolocator: ^13.0.1
  shared_preferences: ^2.3.0
  audioplayers: ^6.0.0
  vibration: ^3.2.0
  url_launcher: ^6.3.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  flutter_local_notifications: ^18.0.0
  flutter_foreground_task: ^8.16.0
  flutter_callkit_incoming: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/logo.png
