/* 🔐 طبقة صلاحيات برنامج «تقفيل الطيارين» — الجزء اللي في الـWire.
 *
 * ═══ الطلب (صاحب النظام 2026-09-01) ═══
 * «عايز أعمل تحكم من تطبيق تقفيل الطيارين بشكل كامل زي ما روح دمشق
 * التطبيق بتاعها فيه تحكم … من داخل التطبيق عايز أعمل صفحة صلاحيات زي
 * اللي في تقفيلة روح دمشق».
 *
 * ═══ النموذج المرجعي ═══
 * `rd_perms` + `DamascusWire::permGroups()`. المفاتيح بتتخزّن JSON،
 * و**القيمة `true` بس هي اللي بتتخزّن** — المفتاح الغايب = ممنوع. ده
 * اللي بيخلّي المقارنة `=== true` كافية ومافيش حالة تالتة.
 *
 * ═══ الفرق عن دمشق — مقصود ═══
 * ① في دمشق `entriesList` بس هي اللي بتقص الأعمدة، وباقي الردود بترجّع
 *    الصف كامل. هنا `entrySave` و`permsSave` بيرجّعوا `{ok}` بس —
 *    مافيش صف بيخرج غير من `month`، فالقص في مكان واحد **كافي فعلًا**.
 *    الحارس بيثبت ده بفحص إن مافيش رد تاني بيحمل صفوف.
 * ② الافتراضي هنا **مش المنع**. مشرف الفرع والمحاسب شغالين على البرنامج
 *    دلوقتي من غير أي صف صلاحيات، والنظام لايف — فمنع افتراضي كان
 *    هيقفل عليهم البرنامج في نص يوم شغل. الافتراضي = اللي بيعملوه
 *    النهاردة بالظبط، والصف لما يتحفظ هو اللي بيضيّق.
 *
 * 🔒 الحارس: ops/test_pilotacct_acl.php
 */
const fs = require('fs');
const F = 'app/Wire/PilotAccountingWire.php';
let s = fs.readFileSync(F, 'utf8');
if (s.includes('function permGroups')) { console.log('🔴 موجود قبل كده'); process.exit(1); }

const L = (...x) => x.join('\n');

const anchor = L(
  "        $t['netDue'] = round($t['gross'] - $c['adv'] - $c['ded'] - $t['deferredDue'], 2);",
  '',
  '        return $t;',
  '    }',
  '}'
);
if (s.split(anchor).length - 1 !== 1) { console.log('🔴 المرساة مش مرة واحدة'); process.exit(1); }

const block = L(
  "        $t['netDue'] = round($t['gross'] - $c['adv'] - $c['ded'] - $t['deferredDue'], 2);",
  '',
  '        return $t;',
  '    }',
  '',
  '    /* ═══════════════════════════════════════════════════════════',
  '       🔐 الصلاحيات — الشاشات والأعمدة والأفعال',
  '',
  '       المفاتيح دي هي **العقد**: الاسم اللي هنا هو نفسه اللي في',
  '       `pilot_acct_perms.perm_keys` ونفسه اللي الواجهة بتتحكم بيه.',
  '       أي مفتاح جديد لازم يتضاف هنا الأول — الواجهة بتبني شاشة',
  '       الصلاحيات من الرد ده مش من قايمة عندها، عشان مايحصلش اختلاف',
  '       بين اللي الأدمن بيعلّم عليه واللي السيرفر بيفهمه.',
  '    ═══════════════════════════════════════════════════════════ */',
  '',
  '    public static function permGroups(): array',
  '    {',
  '        return [',
  "            ['title' => 'الشاشات', 'items' => [",
  "                ['page.daily',    'تقفيل يومي — كل الطيارين في يوم'],",
  "                ['page.pilot',    'كشف الطيار — شهر طيار واحد'],",
  "                ['page.month',    'تقفيلة الشهر والرواتب'],",
  "                ['page.deferred', 'السلف المؤجلة'],",
  '            ]],',
  "            ['title' => 'أعمدة الشيت اليومي وكشف الطيار', 'items' => [",
  "                ['col.in',     'ساعة الحضور'],",
  "                ['col.bout',   'خروج مؤقت (استئذان)'],",
  "                ['col.bin',    'الرجوع من الاستئذان'],",
  "                ['col.out',    'ساعة الانصراف'],",
  "                ['col.hours',  'عدد ساعات العمل'],",
  "                ['col.orders', 'عدد الأوردرات'],",
  "                ['col.svc',    'إجمالي الخدمة'],",
  "                ['col.psvc',   'خدمة الطيار (عمولته)'],",
  "                ['col.net',    'صافي الخدمة'],",
  "                ['col.adv',    'سلف'],",
  "                ['col.ded',    'خصومات'],",
  "                ['col.bonus',  'حوافز'],",
  "                ['col.note',   'ملاحظات'],",
  '            ]],',
  "            ['title' => 'أعمدة تقفيلة الشهر', 'items' => [",
  "                ['mon.hours',      'الساعات وأيام الشغل'],",
  "                ['mon.orders',     'عدد الأوردرات'],",
  "                ['mon.hourPay',    'أجر الساعات'],",
  "                ['mon.commission', 'العمولة'],",
  "                ['mon.salary',     'نصيب الراتب الشهري'],",
  "                ['mon.leave',      'الإجازة المدفوعة'],",
  "                ['mon.bonus',      'الحوافز'],",
  "                ['mon.adv',        'السلف'],",
  "                ['mon.ded',        'الخصومات'],",
  "                ['mon.deferred',   'قسط السلفة المؤجلة'],",
  "                ['mon.net',        'صافي الراتب'],",
  '            ]],',
  "            ['title' => 'الأفعال', 'items' => [",
  "                ['act.edit',     'تعديل الخانات (من غيرها بيتفرّج بس)'],",
  "                ['act.dateNav',  'التنقل بين الأيام والشهور'],",
  "                ['act.deferred', 'تسجيل وتعديل وتحصيل السلف المؤجلة'],",
  "                ['act.lock',     'قفل الشهر وفتحه'],",
  "                ['act.settings', 'تعديل إعدادات البرنامج'],",
  '            ]],',
  '        ];',
  '    }',
  '',
  '    /** كل المفاتيح المعروفة مسطّحة — أي مفتاح برّه دي بيتترمي عند الحفظ */',
  '    public static function permKeys(): array',
  '    {',
  '        $out = [];',
  '        foreach (self::permGroups() as $g) {',
  "            foreach ($g['items'] as $it) {",
  '                $out[] = $it[0];',
  '            }',
  '        }',
  '',
  '        return $out;',
  '    }',
  '',
  '    /**',
  '     * صلاحيات كاملة — الشكل اللي الأدمن (وأي حد لسه مالوش صف) بيشتغل بيه.',
  '     *',
  '     * 🔴 الافتراضي «افتح» مش «اقفل»، وده **مقصود**: البرنامج شغال لايف',
  '     * والمحاسب ومشرفي الفروع بيستعملوه دلوقتي من غير أي صف صلاحيات.',
  '     * منع افتراضي كان معناه إن أول رفعة تقفل عليهم البرنامج في نص يوم',
  '     * شغل. الصف لما يتحفظ هو اللي بيضيّق — مش غيابه.',
  '     */',
  '    public static function fullPermKeys(): array',
  '    {',
  '        $out = [];',
  '        foreach (self::permKeys() as $k) {',
  '            $out[$k] = true;',
  '        }',
  '',
  '        return $out;',
  '    }',
  '',
  '    /** قوالب جاهزة — الواجهة بتعرضها كأزرار، والسيرفر هو مصدرها */',
  '    public static function permPresets(): array',
  '    {',
  '        return [',
  "            'supervisor' => [",
  "                'label' => 'مشرف فرع — يسجّل بس',",
  "                'keys'  => ['page.daily', 'page.pilot',",
  "                    'col.in', 'col.bout', 'col.bin', 'col.out', 'col.hours',",
  "                    'col.orders', 'col.adv', 'col.ded', 'col.bonus', 'col.note',",
  "                    'act.edit', 'act.dateNav'],",
  '            ],',
  "            'accountant' => [",
  "                'label' => 'محاسب — يشوف الفلوس كلها',",
  "                'keys'  => array_values(array_diff(self::permKeys(), ['act.settings'])),",
  '            ],',
  "            'viewer' => [",
  "                'label' => 'متفرّج — يقرا ومايكتبش',",
  "                'keys'  => ['page.daily', 'page.pilot', 'page.month',",
  "                    'col.in', 'col.out', 'col.hours', 'col.orders', 'col.note',",
  "                    'mon.hours', 'mon.orders', 'act.dateNav'],",
  '            ],',
  '        ];',
  '    }',
  '',
  '    /* ═══ القصّ ═══',
  '',
  '       العمود الممنوع بيتشال من الـJSON **خالص** — مش بيترجع صفر ولا',
  '       null. ده فرق مهم: الواجهة بتعرف الفرق بين «صفر» و«مش مسموح»،',
  '       ولو حد فتح أدوات المتصفح مش هيلاقي الرقم مستني في الشبكة.',
  '    ═══ */',
  '',
  '    /** بيقص صف اليوم على الأعمدة المسموحة. `day` و`carry` بيفضلوا دايمًا. */',
  '    public static function filterDay(array $row, array $keys): array',
  '    {',
  '        $map = [',
  "            'in'     => 'col.in',",
  "            'out'    => 'col.out',",
  "            'hours'  => 'col.hours',",
  "            'orders' => 'col.orders',",
  "            'svc'    => 'col.svc',",
  "            'psvc'   => 'col.psvc',",
  "            'net'    => 'col.net',",
  "            'adv'    => 'col.adv',",
  "            'ded'    => 'col.ded',",
  "            'bonus'  => 'col.bonus',",
  "            'note'   => 'col.note',",
  '        ];',
  '        foreach ($map as $field => $key) {',
  '            if (($keys[$key] ?? null) !== true) {',
  '                unset($row[$field]);',
  '            }',
  '        }',
  '',
  '        /* الاستئذان عمودين في الشاشة وحقل واحد في الرد. بيتشال لما',
  '           الاتنين مقفولين — لو واحد منهم مفتوح الشاشة محتاجة القيمة. */',
  "        if (($keys['col.bout'] ?? null) !== true && ($keys['col.bin'] ?? null) !== true) {",
  "            unset($row['perms']);",
  '        }',
  '',
  '        return $row;',
  '    }',
  '',
  '    /** بيقص إجماليات الشهر على الأعمدة المسموحة */',
  '    public static function filterTotals(array $t, array $keys): array',
  '    {',
  '        $map = [',
  "            'hours'         => 'mon.hours',",
  "            'worked'        => 'mon.hours',",
  "            'countedDays'   => 'mon.hours',",
  "            'absent'        => 'mon.hours',",
  "            'orders'        => 'mon.orders',",
  "            'hourRate'      => 'mon.hourPay',",
  "            'hourPay'       => 'mon.hourPay',",
  "            'commission'    => 'mon.commission',",
  "            'monthlySalary' => 'mon.salary',",
  "            'salaryShare'   => 'mon.salary',",
  "            'leaveCap'      => 'mon.leave',",
  "            'leaveDays'     => 'mon.leave',",
  "            'leaveLeft'     => 'mon.leave',",
  "            'leavePay'      => 'mon.leave',",
  "            'bonusDue'      => 'mon.bonus',",
  "            'advanceDue'    => 'mon.adv',",
  "            'deductionDue'  => 'mon.ded',",
  "            'deferredDue'   => 'mon.deferred',",
  "            'deferredLeft'  => 'mon.deferred',",
  "            'gross'         => 'mon.net',",
  "            'netDue'        => 'mon.net',",
  '        ];',
  '        foreach ($map as $field => $key) {',
  '            if (($keys[$key] ?? null) !== true) {',
  '                unset($t[$field]);',
  '            }',
  '        }',
  '',
  '        return $t;',
  '    }',
  '}'
);

s = s.replace(anchor, block);
fs.writeFileSync(F, s);
console.log('✅ طبقة الصلاحيات اتضافت للـWire');
