/* 👥 تقفيل الموظفين — الطبقة السيرفرية.
 *
 * ═══ الطلب (صاحب النظام 2026-09-01) ═══
 * «زي ما الطيارين لهم تقفيلة ضيف كل الموظفين كمان بشكل أوتوماتيك —
 * المشرف بتاع الفرع له وقت تسجيل دخول من أول ما يفتح المتصفح بتاعه...
 * راجع تقفيلة روح دمشق فيها شغل حسابات مهم لازم توصله».
 *
 * ═══ مصدر الحضور ═══
 * `attendance_sessions` — بيتكتب تلقائيًا من branch.html وcallcenter.html
 * وtiar.html (check-in عند الفتح، heartbeat كل شوية، check-out عند القفل،
 * وcron بيقفل الجلسة المفتوحة على آخر نبضة). يعني «من أول ما يفتح
 * المتصفح» موجودة فعلًا — إحنا بنقراها بس.
 *
 * ═══ حسابات دمشق ═══
 * مش بنكتب معادلات جديدة: `W::dayRow` و`W::monthTotals` هما نقل دمشق
 * اللي اتعمل للطيارين (أجر الساعات، الراتب الشهري مقسوم على أيام الشغل،
 * الإجازة المدفوعة، صافي المستحق). الموظف بيتمرر لنفس الدالتين بشكل
 * «طيار بلا أوردرات»: عمولة صفر وخدمة صفر — فالمعادلات هي هي حرفيًا.
 *
 * ═══ الاستئذان التلقائي ═══
 * الموظف ممكن يقفل المتصفح الضهر ويرجع — جلستين في اليوم. الفجوة بين
 * الجلسات بتتسجّل **استئذانًا تلقائيًا**: `auto.hours` = من أول حضور
 * لآخر انصراف (span)، و`auto.perms` = الفجوات. `dayRow` بيطرح فترات
 * الاستئذان من الـspan → الناتج = مجموع الجلسات الفعلية بالظبط، والشاشة
 * بتعرض الفجوات في عمودي الاستئذان زي الطيارين.
 *
 * ═══ يوم الموظف = اليوم الميلادي بتوقيت القاهرة ═══
 * مش يوم الطيارين التجاري (٩ص): `attendance_sessions.session_date`
 * بيتختم بـ`cairoDayKey()` (منتصف الليل)، ودي نفس الأيام اللي شاشة
 * الحضور في الإدارة والفروع بتعرضها. لو حسبنا بيوم ٩ص كان اليوم هنا
 * غير اليوم هناك ونفس الجلسة تبان في يومين مختلفين.
 *
 * ═══ سعر ساعة الموظف = بتاعه هو بس ═══
 * `hourRateOf` بيرجع لسعر الساعة الموحّد في الإعدادات لو سعر الشخص صفر.
 * الإعداد ده اتعمل للطيارين — لو سرى على الموظفين كان أي رقم يتكتب فيه
 * هيدّي الكول سنتر أجر ساعات طيار من غير ما حد ياخد باله. فبنمرر نسخة
 * من الإعدادات بسعر صفر: موظف من غير سعر ساعة = أجر ساعات صفر، صريحة.
 *
 * 🔒 الحارس: ops/test_staff_closeout.php
 */
const fs = require('fs');
let bad = 0;
const L = (...x) => x.join('\n');
const BUF = {};
const load = f => (BUF[f] !== undefined ? BUF[f] : (BUF[f] = fs.readFileSync(f, 'utf8')));
const one = (file, old, neu, label) => {
  const s = load(file);
  const n = s.split(old).length - 1;
  if (n !== 1) { console.log('  🔴 ' + label + ': اتلقت ' + n + ' مرة'); bad++; return; }
  BUF[file] = s.replace(old, neu);
  console.log('  ✓ ' + label);
};

const CTL = 'app/Http/Controllers/Api/PilotAccountingController.php';
const WIRE = 'app/Wire/PilotAccountingWire.php';
const RT = 'routes/api.php';

if (load(CTL).includes('staffMonth')) { console.log('🔴 موجود قبل كده'); process.exit(1); }

/* ═══ ① الـWire: شاشة جديدة في الصلاحيات ═══ */
one(WIRE,
  L(
    "            ['title' => 'الشاشات', 'items' => [",
    "                ['page.daily',    'تقفيل يومي — كل الطيارين في يوم'],",
    "                ['page.pilot',    'كشف الطيار — شهر طيار واحد'],",
    "                ['page.month',    'تقفيلة الشهر والرواتب'],",
    "                ['page.deferred', 'السلف المؤجلة'],",
    '            ]],'
  ),
  L(
    "            ['title' => 'الشاشات', 'items' => [",
    "                ['page.daily',    'تقفيل يومي — كل الطيارين في يوم'],",
    "                ['page.pilot',    'كشف الطيار — شهر طيار واحد'],",
    "                ['page.month',    'تقفيلة الشهر والرواتب'],",
    "                ['page.deferred', 'السلف المؤجلة'],",
    "                ['page.staff',    'تقفيل الموظفين — الحضور من المتصفح'],",
    '            ]],'
  ),
  '① مفتاح page.staff في الصلاحيات'
);

/* ═══ ② الكنترولر: قسم الموظفين كامل قبل قفلة الكلاس ═══ */
one(CTL,
  L(
    '        return $p;',
    '    }',
    '}'
  ),
  L(
    '        return $p;',
    '    }',
    '',
    '    /* ═══════════════════════════════════════════════════════════',
    '       👥 تقفيل الموظفين — الحضور من جلسات المتصفح',
    '',
    '       نفس نموذج تقفيل الطيارين حرفيًا، بفرقين:',
    '       ① المصدر `attendance_sessions` (بيتكتب تلقائيًا من فتح صفحة',
    '          الفرع/الكول سنتر/الإدارة) بدل الورديات والأوردرات.',
    '       ② اليوم = اليوم الميلادي بتوقيت القاهرة (نفس شاشة الحضور',
    '          الموجودة في الإدارة) — مش يوم الطيارين التجاري (٩ص).',
    '',
    '       الحسابات نفسها (`dayRow`/`monthTotals`) — معادلات دمشق اللي',
    '       اتنقلت للطيارين بتشتغل هنا زي ما هي: الموظف = طيار بلا',
    '       أوردرات (عمولة صفر وخدمة صفر).',
    '    ═══════════════════════════════════════════════════════════ */',
    '',
    "    /** الأدوار اللي بتدخل تقفيلة الموظفين — الأدمن مستثنى بطلب صريح */",
    "    private const STAFF_ROLES = ['branch', 'callcenter', 'accountant', 'hr', 'pilot_supervisor'];",
    '',
    '    /** GET /api/pilot-accounting/staff-month?month=&branchId= */',
    '    public function staffMonth(Request $request): JsonResponse',
    '    {',
    '        $actor = $request->actorOrFail();',
    '        $acl   = $this->aclOf($actor);',
    "        $this->need($acl, 'page.staff', 'على تقفيل الموظفين');",
    '',
    "        $ym  = $this->monthArg((string) $request->query('month', ''));",
    '        $set = $this->settings();',
    '',
    "        $branchId = $request->query('branchId');",
    "        $branchId = $branchId !== null && $branchId !== '' ? (int) $branchId : null;",
    "        if ($actor->role === 'branch') {",
    '            $branchId = (int) ($actor->branchId ?? 0);   // مشرف الفرع مقفول على فرعه',
    '        }',
    "        if ($acl['branches'] && $branchId !== null && ! in_array($branchId, $acl['branches'], true)) {",
    "            throw ApiException::forbidden('الفرع ده مش مسموحلك بيه');",
    '        }',
    '',
    "        $ph  = implode(',', array_fill(0, count(self::STAFF_ROLES), '?'));",
    '        $sql = "SELECT u.id, u.username, u.name, u.role, u.branch_id, b.name AS branch_name,',
    '                       u.hour_rate, u.monthly_salary, u.paid_leave_days',
    '                  FROM users u LEFT JOIN branches b ON b.id = u.branch_id',
    '                 WHERE u.blocked = 0 AND u.role IN ({$ph})";',
    '        $args = self::STAFF_ROLES;',
    '        if ($branchId !== null) {',
    "            $sql .= ' AND u.branch_id = ?';",
    '            $args[] = $branchId;',
    "        } elseif ($acl['branches']) {",
    '            /* الصلاحية محدودة بفروع — الموظف بلا فرع (كول سنتر مثلًا)',
    '               بيختفي، وده مقصود: مالوش فرع = مش من فروعه. */',
    "            $sql .= ' AND u.branch_id IN (' . implode(',', array_fill(0, count($acl['branches']), '?')) . ')';",
    "            $args = array_merge($args, $acl['branches']);",
    '        }',
    "        $sql .= ' ORDER BY u.role, u.username';",
    '        $staff = array_map(fn ($r) => (array) $r, DB::select($sql, $args));',
    '',
    '        $nd      = W::daysInMonth($ym);',
    '        /* أيام محسوبة بيوم ميلادي (dayStart=0) — مش يوم الطيارين */',
    '        $counted = W::countedDays($ym, 0);',
    '        $auto    = $this->staffAutoMatrix(array_column($staff, \'username\'), $ym);',
    '        $entries = $this->staffEntriesOf($ym, array_map(fn ($u) => (int) $u[\'id\'], $staff));',
    '',
    '        /* سعر الساعة الموحّد بتاع الطيارين مايسريش على الموظفين —',
    '           موظف من غير سعر ساعة أجره بالساعة صفر، صريحة مش بالوراثة. */',
    "        $staffSet = $set;",
    "        $staffSet['hourRate'] = 0.0;",
    '',
    '        $out = [];',
    '        foreach ($staff as $u) {',
    "            $uid = (int) $u['id'];",
    '            $days = [];',
    '            for ($d = 1; $d <= $nd; $d++) {',
    "                $e     = $entries[$uid][$d] ?? [];",
    "                $perms = $e['perms'] ?? ($auto[$u['username']][$d]['perms'] ?? []);",
    "                $days[] = W::dayRow($d, $auto[$u['username']][$d] ?? [], $e, $perms);",
    '            }',
    '',
    '            /* الموظف = طيار بلا أوردرات — نفس معادلات دمشق بالظبط */',
    '            $totals = W::monthTotals($days, [',
    "                'commission_type'  => 'fixed',",
    "                'commission_value' => 0,",
    "                'hour_rate'        => (float) $u['hour_rate'],",
    "                'monthly_salary'   => (float) $u['monthly_salary'],",
    "                'paid_leave_days'  => (int) $u['paid_leave_days'],",
    '            ], [',
    "                'settings'     => $staffSet,",
    "                'countedDays'  => $counted,",
    "                'shiftHours'   => $set['shiftHours'],",
    "                'deferredDue'  => 0.0,",
    "                'deferredLeft' => 0.0,",
    '            ]);',
    '',
    "            if (! $acl['full']) {",
    "                $days   = array_map(fn (array $r): array => W::filterDay($r, $acl['keys']), $days);",
    "                $totals = W::filterTotals($totals, $acl['keys']);",
    '            }',
    '',
    '            $out[] = [',
    "                'userId'     => $uid,",
    "                'username'   => $u['username'],",
    "                'name'       => $u['name'],",
    "                'role'       => $u['role'],",
    "                'branchId'   => $u['branch_id'] !== null ? (int) $u['branch_id'] : null,",
    "                'branchName' => $u['branch_name'],",
    "                'hourRate'   => round((float) $u['hour_rate'], 2),",
    "                'monthlySalary'  => round((float) $u['monthly_salary'], 2),",
    "                'paidLeaveDays'  => (int) $u['paid_leave_days'],",
    "                'days'       => $days,",
    "                'totals'     => $totals,",
    '            ];',
    '        }',
    '',
    '        return ApiResponse::out([',
    "            'ok'          => true,",
    "            'serverNow'   => WireTime::toWire(WireTime::nowDb()),",
    "            'month'       => $ym,",
    "            'branchId'    => $branchId,",
    "            'settings'    => $set,",
    "            'locked'      => $this->monthLocked($ym, $branchId),",
    "            'daysInMonth' => $nd,",
    "            'countedDays' => $counted,",
    "            'staff'       => $out,",
    "            'acl'         => ['keys' => (object) $acl['keys'], 'branches' => $acl['branches'],",
    "                              'full' => $acl['full'], 'isAdmin' => $actor->role === 'admin'],",
    '        ]);',
    '    }',
    '',
    '    /**',
    '     * حضور الشهر من جلسات المتصفح: [username][day] = {in, out, hours, perms}.',
    '     *',
    '     * `in` أول حضور و`out` آخر انصراف (أو آخر نبضة للجلسة المفتوحة —',
    '     * نفس اللي cron الإغلاق التلقائي بيقفل عليه). `hours` هي الـspan',
    '     * الكامل، والفجوات بين الجلسات بتطلع `perms` — فـ`dayRow` لما',
    '     * يطرحها بيرجع مجموع الجلسات الفعلية، والاستئذان باين في عموده.',
    '     */',
    '    private function staffAutoMatrix(array $usernames, string $ym): array',
    '    {',
    '        if (! $usernames) {',
    '            return [];',
    '        }',
    "        $ph = implode(',', array_fill(0, count($usernames), '?'));",
    '        $rows = DB::select(',
    '            "SELECT username, session_date, check_in, check_out, last_seen',
    '               FROM attendance_sessions',
    '              WHERE session_date LIKE ? AND username IN ({$ph})',
    '              ORDER BY username, check_in",',
    "            array_merge([$ym . '-%'], $usernames)",
    '        );',
    '',
    '        $sessions = [];',
    '        foreach ($rows as $r) {',
    '            $day = (int) substr((string) $r->session_date, 8, 2);',
    '            /* dayStart=0: تحويل قاهرة صافي من غير زحزحة اليوم التجاري */',
    '            $in  = W::bizMoment((string) $r->check_in, 0);',
    '            $out = W::bizMoment((string) ($r->check_out ?? $r->last_seen ?? $r->check_in), 0);',
    '            if ($in === null || $out === null) {',
    '                continue;',
    '            }',
    "            $sessions[$r->username][$day][] = ['in' => $in['hm'], 'out' => $out['hm']];",
    '        }',
    '',
    '        $matrix = [];',
    '        foreach ($sessions as $uname => $days) {',
    '            foreach ($days as $day => $list) {',
    '                /* مترتبين بـcheck_in من الاستعلام */',
    "                $first = $list[0]['in'];",
    "                $last  = $first;",
    '                $perms = [];',
    '                foreach ($list as $i => $s) {',
    "                    $o = W::parseHm($s['out']) ?? 0;",
    '                    if ($o >= (W::parseHm($last) ?? 0)) {',
    "                        $last = $s['out'];",
    '                    }',
    '                    if ($i > 0) {',
    "                        $prevOut = $list[$i - 1]['out'];",
    '                        /* فجوة حقيقية بس — دقيقة فأكتر */',
    "                        if ((W::parseHm($s['in']) ?? 0) > (W::parseHm($prevOut) ?? 0)) {",
    "                            $perms[] = ['out' => $prevOut, 'in' => $s['in']];",
    '                        }',
    '                    }',
    '                }',
    '                $span = ((W::parseHm($last) ?? 0) - (W::parseHm($first) ?? 0)) / 60;',
    '                $matrix[$uname][$day] = [',
    "                    'in'    => $first,",
    "                    'out'   => $last,",
    "                    'hours' => round(max(0, $span), 2),",
    "                    'perms' => $perms,",
    '                ];',
    '            }',
    '        }',
    '',
    '        return $matrix;',
    '    }',
    '',
    '    /** صفوف الشيت اليدوية + فترات استئذانها — مرآة entriesOf */',
    '    private function staffEntriesOf(string $ym, array $ids): array',
    '    {',
    '        if (! $ids) {',
    '            return [];',
    '        }',
    "        $ph = implode(',', array_fill(0, count($ids), '?'));",
    '        $rows = DB::select(',
    '            "SELECT * FROM staff_day_entries WHERE month = ? AND user_id IN ({$ph})",',
    '            array_merge([$ym], $ids)',
    '        );',
    '        $out = [];',
    '        $byEntry = [];',
    '        foreach ($rows as $r) {',
    '            $r = (array) $r;',
    "            $out[(int) $r['user_id']][(int) $r['day']] = $r;",
    "            $byEntry[(int) $r['id']] = [(int) $r['user_id'], (int) $r['day']];",
    '        }',
    '        if ($byEntry) {',
    "            $eph = implode(',', array_fill(0, count($byEntry), '?'));",
    '            foreach (DB::select(',
    '                "SELECT * FROM staff_day_perms WHERE entry_id IN ({$eph}) ORDER BY id",',
    '                array_keys($byEntry)',
    '            ) as $p) {',
    '                $p = (array) $p;',
    "                [$uid, $day] = $byEntry[(int) $p['entry_id']];",
    "                $out[$uid][$day]['perms'][] = ['out' => $p['perm_out'], 'in' => $p['perm_in']];",
    '            }',
    '        }',
    '',
    '        return $out;',
    '    }',
    '',
    '    /** الموظف موجود ومن أدوار التقفيلة وفي نطاق الطالب — مرآة pilotInScope */',
    '    private function staffInScope(Actor $actor, int $userId): array',
    '    {',
    "        $u = DB::select('SELECT id, username, role, branch_id FROM users WHERE id = ? AND blocked = 0', [$userId])[0] ?? null;",
    '        if (! $u || ! in_array((string) $u->role, self::STAFF_ROLES, true)) {',
    "            throw ApiException::notFound('الموظف غير موجود في التقفيلة');",
    '        }',
    '        $u = (array) $u;',
    "        if ($actor->role === 'branch' && (int) ($u['branch_id'] ?? 0) !== (int) ($actor->branchId ?? -1)) {",
    "            throw ApiException::forbidden('الموظف ده مش في فرعك');",
    '        }',
    '        $acl = $this->aclOf($actor);',
    "        if ($acl['branches'] && ! in_array((int) ($u['branch_id'] ?? 0), $acl['branches'], true)) {",
    "            throw ApiException::forbidden('الموظف ده في فرع مش مسموحلك بيه');",
    '        }',
    '',
    '        return $u;',
    '    }',
    '',
    '    /**',
    '     * POST /api/pilot-accounting/staff-entry — {month, userId, day, field, value}',
    '     * نفس عقد entrySave: القيمة الفاضية بتمسح التدخّل ويرجع التلقائي.',
    '     */',
    '    public function staffEntrySave(Request $request): JsonResponse',
    '    {',
    '        $actor = $request->actorOrFail();',
    '        $b     = $request->json()->all();',
    '',
    "        $ym    = $this->monthArg((string) ($b['month'] ?? ''));",
    "        $uid   = (int) ($b['userId'] ?? 0);",
    "        $day   = (int) ($b['day'] ?? 0);",
    "        $field = (string) ($b['field'] ?? '');",
    '',
    '        /* خانات الموظف — مافيش أوردرات ولا خدمة هنا */',
    '        $COLS = [',
    "            'in'    => 'time_in_override',",
    "            'out'   => 'time_out_override',",
    "            'hours' => 'hours_override',",
    "            'adv'   => 'advance_extra',",
    "            'ded'   => 'deduction_extra',",
    "            'bonus' => 'bonus_extra',",
    "            'note'  => 'note',",
    '        ];',
    '        if (! isset($COLS[$field])) {',
    "            throw new ApiException('خانة مش معروفة');",
    '        }',
    '        if ($day < 1 || $day > W::daysInMonth($ym)) {',
    "            throw new ApiException('اليوم مش في الشهر ده');",
    '        }',
    '',
    '        $acl = $this->aclOf($actor);',
    "        $this->need($acl, 'act.edit', 'تعديل الخانات');",
    "        $this->need($acl, 'col.' . $field, 'الكتابة في الخانة دي');",
    '',
    '        $u = $this->staffInScope($actor, $uid);',
    "        $this->assertUnlocked($ym, $u['branch_id'] !== null ? (int) $u['branch_id'] : null);",
    '',
    "        $raw = $b['value'] ?? null;",
    '        $val = null;',
    "        if ($raw !== null && $raw !== '') {",
    "            if (in_array($field, ['in', 'out'], true)) {",
    '                if (W::parseHm((string) $raw) === null) {',
    "                    throw new ApiException('الوقت لازم يكون بصيغة HH:MM');",
    '                }',
    '                $val = trim((string) $raw);',
    "            } elseif ($field === 'note') {",
    '                $val = mb_substr(trim((string) $raw), 0, 2000);',
    '            } else {',
    '                $val = round((float) $raw, 2);',
    '            }',
    '        }',
    '',
    '        $now = WireTime::nowDb();',
    '        DB::statement(',
    '            "INSERT INTO staff_day_entries (month, user_id, day, `{$COLS[$field]}`, updated_by, updated_at, created_at)',
    '             VALUES (?,?,?,?,?,?,?)',
    '             ON DUPLICATE KEY UPDATE `{$COLS[$field]}` = VALUES(`{$COLS[$field]}`),',
    '                                     updated_by = VALUES(updated_by), updated_at = VALUES(updated_at)",',
    '            [$ym, $uid, $day, $val, $actor->username, $now, $now]',
    '        );',
    '',
    '        if ($val === null) {',
    '            $this->staffCleanupEntry($ym, $uid, $day);',
    '        }',
    '',
    "        return ApiResponse::out(['ok' => true, 'cleared' => $val === null]);",
    '    }',
    '',
    '    /** الصف الفاضي بيتحذف — «فيه صف» لازم تفضل تدل على «حد تدخّل» */',
    '    private function staffCleanupEntry(string $ym, int $uid, int $day): void',
    '    {',
    '        $r = DB::select(',
    "            'SELECT * FROM staff_day_entries WHERE month = ? AND user_id = ? AND day = ?',",
    '            [$ym, $uid, $day]',
    '        )[0] ?? null;',
    '        if (! $r) {',
    '            return;',
    '        }',
    '        $r = (array) $r;',
    "        foreach (['time_in_override', 'time_out_override', 'hours_override',",
    "                  'advance_extra', 'deduction_extra', 'bonus_extra'] as $c) {",
    '            if ($r[$c] !== null) {',
    '                return;',
    '            }',
    '        }',
    "        if (trim((string) ($r['note'] ?? '')) !== '') {",
    '            return;',
    '        }',
    "        if (DB::select('SELECT id FROM staff_day_perms WHERE entry_id = ? LIMIT 1', [(int) $r['id']])) {",
    '            return;',
    '        }',
    "        DB::delete('DELETE FROM staff_day_entries WHERE id = ?', [(int) $r['id']]);",
    '    }',
    '',
    '    /**',
    '     * POST /api/pilot-accounting/staff-perms — {month, userId, day, periods:[{out,in}]}',
    '     * بيستبدل فترات الاستئذان اليدوية لليوم كلها — نفس عقد permsSave.',
    '     */',
    '    public function staffPermsSave(Request $request): JsonResponse',
    '    {',
    '        $actor = $request->actorOrFail();',
    '',
    '        $acl = $this->aclOf($actor);',
    "        $this->need($acl, 'act.edit', 'تعديل الخانات');",
    "        if (! $this->can($acl, 'col.bout') && ! $this->can($acl, 'col.bin')) {",
    "            throw ApiException::forbidden('مالكش صلاحية على خانات الاستئذان — كلّم الإدارة');",
    '        }',
    '        $b = $request->json()->all();',
    '',
    "        $ym  = $this->monthArg((string) ($b['month'] ?? ''));",
    "        $uid = (int) ($b['userId'] ?? 0);",
    "        $day = (int) ($b['day'] ?? 0);",
    '        if ($day < 1 || $day > W::daysInMonth($ym)) {',
    "            throw new ApiException('اليوم مش في الشهر ده');",
    '        }',
    '        $u = $this->staffInScope($actor, $uid);',
    "        $this->assertUnlocked($ym, $u['branch_id'] !== null ? (int) $u['branch_id'] : null);",
    '',
    "        $periods = is_array($b['periods'] ?? null) ? $b['periods'] : [];",
    '        $clean = [];',
    '        foreach ($periods as $p) {',
    "            $o = trim((string) ($p['out'] ?? ''));",
    "            $i = trim((string) ($p['in'] ?? ''));",
    "            if ($o === '' && $i === '') {",
    '                continue;',
    '            }',
    "            if (($o !== '' && W::parseHm($o) === null) || ($i !== '' && W::parseHm($i) === null)) {",
    "                throw new ApiException('وقت الاستئذان لازم يكون بصيغة HH:MM');",
    '            }',
    '            $clean[] = [$o ?: null, $i ?: null];',
    '        }',
    '        if (count($clean) > 20) {',
    "            throw new ApiException('أقصى عدد فترات استئذان لليوم 20');",
    '        }',
    '',
    '        DB::transaction(function () use ($ym, $uid, $day, $clean, $actor): void {',
    '            $now = WireTime::nowDb();',
    '            DB::statement(',
    "                'INSERT INTO staff_day_entries (month, user_id, day, updated_by, updated_at, created_at)",
    '                 VALUES (?,?,?,?,?,?)',
    "                 ON DUPLICATE KEY UPDATE updated_by = VALUES(updated_by), updated_at = VALUES(updated_at)',",
    '                [$ym, $uid, $day, $actor->username, $now, $now]',
    '            );',
    '            $eid = (int) DB::select(',
    "                'SELECT id FROM staff_day_entries WHERE month = ? AND user_id = ? AND day = ?',",
    '                [$ym, $uid, $day]',
    '            )[0]->id;',
    '',
    "            DB::delete('DELETE FROM staff_day_perms WHERE entry_id = ?', [$eid]);",
    '            foreach ($clean as [$o, $i]) {',
    '                DB::insert(',
    "                    'INSERT INTO staff_day_perms (entry_id, perm_out, perm_in) VALUES (?,?,?)',",
    '                    [$eid, $o, $i]',
    '                );',
    '            }',
    '        });',
    '',
    '        $this->staffCleanupEntry($ym, $uid, $day);',
    '',
    "        return ApiResponse::out(['ok' => true, 'count' => count($clean)]);",
    '    }',
    '}'
  ),
  '② قسم الموظفين في الكنترولر'
);

/* ═══ ③ المسارات ═══ */
one(RT,
  L(
    "Route::get('pilot-accounting/acl', [PilotAccountingController::class, 'aclList'])",
    "    ->middleware('role:admin');"
  ),
  L(
    "/* 👥 تقفيل الموظفين — نفس أدوار تقفيلة الطيارين، والكنترولر بيقصّ",
    "   بالصلاحيات (page.staff) وبنطاق الفرع. الحضور من attendance_sessions",
    "   اللي بيتكتب تلقائيًا من فتح صفحات الفرع والكول سنتر والإدارة. */",
    "Route::get('pilot-accounting/staff-month', [PilotAccountingController::class, 'staffMonth'])",
    "    ->middleware('role:admin,branch,accountant');",
    "Route::post('pilot-accounting/staff-entry', [PilotAccountingController::class, 'staffEntrySave'])",
    "    ->middleware('role:admin,branch,accountant');",
    "Route::post('pilot-accounting/staff-perms', [PilotAccountingController::class, 'staffPermsSave'])",
    "    ->middleware('role:admin,branch,accountant');",
    '',
    "Route::get('pilot-accounting/acl', [PilotAccountingController::class, 'aclList'])",
    "    ->middleware('role:admin');"
  ),
  '③ المسارات'
);

/* ═══ ④ تسجيلهم في بوابة التغطية ═══ */
one('app/Console/Commands/RouteCoverage.php',
  "        'GET /api/pilot-accounting/acl' =>",
  L(
    "        'GET /api/pilot-accounting/staff-month' =>",
    "            'تقفيلة الموظفين (طلب صاحب النظام 2026-09-01: «زي ما الطيارين لهم تقفيلة ضيف كل الموظفين بشكل أوتوماتيك») — الحضور من جلسات المتصفح في attendance_sessions، والحسابات نفس معادلات دمشق المنقولة للطيارين',",
    '',
    "        'POST /api/pilot-accounting/staff-entry' =>",
    "            'تدخّل يدوي في خانة من شيت الموظف — نفس عقد pilot-accounting/entry',",
    '',
    "        'POST /api/pilot-accounting/staff-perms' =>",
    "            'فترات استئذان يدوية ليوم موظف — بتستبدل فجوات الجلسات التلقائية',",
    '',
    "        'GET /api/pilot-accounting/acl' =>"
  ),
  '④ التغطية'
);

if (bad) { console.log('\n🔴 ' + bad + ' مشكلة — مالمستش ولا ملف'); process.exit(1); }
Object.keys(BUF).forEach(f => fs.writeFileSync(f, BUF[f]));
console.log('\n✅ طبقة الموظفين السيرفرية — ' + Object.keys(BUF).length + ' ملفات');
